// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {
    CommitmentEnvelope, Sample, SampleSource, VerdictLib, VerdictState
} from "../src/VerdictLib.sol";

/// @notice G2 (PRD §22): the Solidity evaluator and `packages/reference` must
/// agree on 10,000 generated commitment and sample pairs, with zero divergence.
/// @dev The pairs and the reference verdicts are generated by
/// `scripts/differential.ts`, which also runs this test. Field order here must
/// match `CASE_TUPLE` in that file; `abi.decode` is positional.
contract DifferentialTest is Test {
    struct Case {
        uint32 maxSpread;
        uint128 minSize;
        uint64 start;
        uint64 end;
        uint128 bid;
        uint128 ask;
        uint128 bidSize;
        uint128 askSize;
        uint64 blockNumber;
        bytes32 blockHash;
        uint8 source;
        uint8 expected;
        uint8 expectedBreach;
    }

    string internal constant FIXTURES = "contracts/test/fixtures/";

    /// @dev G2 is `pnpm test:differential`, which regenerates the fixtures from
    /// the current `packages/reference` and then runs this test. Invoked on its
    /// own with no fixtures present — a fresh clone, or CI's `contracts` job —
    /// this skips rather than fails, because replaying vectors that were not
    /// generated in this run would compare against a stale reference.
    function test_evaluators_agree() public {
        string memory manifest = string.concat(FIXTURES, "differential.manifest");
        if (!vm.exists(manifest)) {
            // solhint-disable-next-line no-console
            vm.skip(true);
        }
        uint256 chunkCount = vm.parseUint(vm.trim(vm.readFile(manifest)));
        assertGt(chunkCount, 0, "no differential fixtures: run pnpm test:differential");

        uint256 checked;
        for (uint256 chunk = 0; chunk < chunkCount; ++chunk) {
            string memory path =
                string.concat(FIXTURES, "differential.", _pad3(chunk), ".hex");
            Case[] memory cases = abi.decode(vm.parseBytes(vm.trim(vm.readFile(path))), (Case[]));

            for (uint256 i = 0; i < cases.length; ++i) {
                Case memory c = cases[i];
                CommitmentEnvelope memory envelope = CommitmentEnvelope({
                    maxSpread: c.maxSpread,
                    minSize: c.minSize,
                    start: c.start,
                    end: c.end
                });
                Sample memory sample = Sample({
                    bid: c.bid,
                    ask: c.ask,
                    bidSize: c.bidSize,
                    askSize: c.askSize,
                    blockNumber: c.blockNumber,
                    blockHash: c.blockHash,
                    source: SampleSource(c.source)
                });

                VerdictState got = VerdictLib.verdict(envelope, sample);
                // Built only on mismatch, and in its own frame: the message is long
                // enough to exhaust the stack if it is assembled inline.
                if (uint256(got) != uint256(c.expected)) {
                    _reportDivergence(checked, c, got);
                }
                // The breach classification is compared for the same pair: it
                // decides whether a bond forfeits, so it carries the same weight
                // as the verdict and gets the same agreement gate.
                if ((VerdictLib.isBreach(got) ? uint8(1) : uint8(0)) != c.expectedBreach) {
                    _reportDivergence(checked, c, got);
                }
                ++checked;
            }
        }

        assertEq(checked, 10_000, "G2 requires 10,000 pairs (PRD 22 G2)");
    }

    /// @dev A divergence has to be reproducible from the CI log alone, so the
    /// whole pair goes into the failure message.
    function _reportDivergence(uint256 index, Case memory c, VerdictState got) private pure {
        string memory envelopePart = string.concat(
            "divergence at pair ",
            vm.toString(index),
            ": solidity=",
            vm.toString(uint256(got)),
            " reference=",
            vm.toString(uint256(c.expected)),
            " | maxSpread=",
            vm.toString(uint256(c.maxSpread)),
            " minSize=",
            vm.toString(uint256(c.minSize)),
            " window=[",
            vm.toString(uint256(c.start)),
            ",",
            vm.toString(uint256(c.end)),
            "]"
        );
        string memory samplePart = string.concat(
            " bid=",
            vm.toString(uint256(c.bid)),
            " ask=",
            vm.toString(uint256(c.ask)),
            " bidSize=",
            vm.toString(uint256(c.bidSize)),
            " askSize=",
            vm.toString(uint256(c.askSize)),
            " block=",
            vm.toString(uint256(c.blockNumber)),
            " blockHash=",
            vm.toString(c.blockHash),
            " source=",
            vm.toString(uint256(c.source))
        );
        revert(string.concat(envelopePart, samplePart));
    }

    function _pad3(uint256 value) private pure returns (string memory) {
        if (value < 10) {
            return string.concat("00", vm.toString(value));
        }
        if (value < 100) {
            return string.concat("0", vm.toString(value));
        }
        return vm.toString(value);
    }
}
